/**
 * Wearable static metadata for all 287 wearables
 * Only contains name and category — stats/rarity/faction are fetched from chain
 */

export type WearableCategory = 'background' | 'body' | 'eyes' | 'head' | 'hand' | 'clothes' | 'face' | 'mouth';

export interface WearableConfig {
  name: string;
  category: WearableCategory;
}

export const WEARABLE_DATA: Record<number, WearableConfig> = {
  // Backgrounds (0-24)
  0: { name: 'Abyss', category: 'background' },
  1: { name: 'Aurora Pink', category: 'background' },
  2: { name: 'Bioluminescent', category: 'background' },
  3: { name: 'Blood Reef', category: 'background' },
  4: { name: 'Crimson Deep', category: 'background' },
  5: { name: 'Cyber Void', category: 'background' },
  6: { name: 'Deep Purple', category: 'background' },
  7: { name: 'Ember Glow', category: 'background' },
  8: { name: 'Frozen Abyss', category: 'background' },
  9: { name: 'Glacial Mint', category: 'background' },
  10: { name: 'Magma Core', category: 'background' },
  11: { name: 'Midnight Navy', category: 'background' },
  12: { name: 'Moonstone', category: 'background' },
  13: { name: 'Neon Rift', category: 'background' },
  14: { name: 'Ocean Depth', category: 'background' },
  15: { name: 'Pearl', category: 'background' },
  16: { name: 'PHAROS Gold', category: 'background' },
  17: { name: 'Plasma Storm', category: 'background' },
  18: { name: 'Sea Foam', category: 'background' },
  19: { name: 'Sunset Coral', category: 'background' },
  20: { name: 'Toxic Kelp', category: 'background' },
  21: { name: 'Twilight Blue', category: 'background' },
  22: { name: 'Venom Tide', category: 'background' },
  23: { name: 'Void Iris', category: 'background' },
  24: { name: 'Volcano Red', category: 'background' },
  // Bodies (25-61)
  25: { name: 'BTC Orange', category: 'body' },
  26: { name: 'Black White', category: 'body' },
  27: { name: 'Blue', category: 'body' },
  28: { name: 'Bronze', category: 'body' },
  29: { name: 'Celestial White', category: 'body' },
  30: { name: 'Coral Pink', category: 'body' },
  31: { name: 'Diamond', category: 'body' },
  32: { name: 'ETH Purple', category: 'body' },
  33: { name: 'Electric', category: 'body' },
  34: { name: 'Holographic', category: 'body' },
  35: { name: 'Ice Crystal', category: 'body' },
  36: { name: 'Ivory', category: 'body' },
  37: { name: 'Jade Green', category: 'body' },
  38: { name: 'Lava', category: 'body' },
  39: { name: 'Lavender', category: 'body' },
  40: { name: 'Matrix Green', category: 'body' },
  41: { name: 'Obsidian', category: 'body' },
  42: { name: 'Ocean Blue', category: 'body' },
  43: { name: 'Phantom', category: 'body' },
  44: { name: 'Pink', category: 'body' },
  45: { name: 'Pure Gold', category: 'body' },
  46: { name: 'Rainbow', category: 'body' },
  47: { name: 'Rose Gold', category: 'body' },
  48: { name: 'Sea Green', category: 'body' },
  49: { name: 'Silver Steel', category: 'body' },
  50: { name: 'Sky Cyan', category: 'body' },
  51: { name: 'Sunset Orange', category: 'body' },
  52: { name: 'Transparent', category: 'body' },
  53: { name: 'Void Black', category: 'body' },
  54: { name: 'Water Body', category: 'body' },
  55: { name: 'Cow', category: 'body' },
  56: { name: 'Tiger', category: 'body' },
  57: { name: 'Ice', category: 'body' },
  58: { name: 'Galaxy', category: 'body' },
  59: { name: 'Hole', category: 'body' },
  60: { name: 'Bitcoin', category: 'body' },
  61: { name: 'Rainbow', category: 'body' },
  // Clothes (62-104)
  62: { name: 'Camouflage Outfit', category: 'clothes' },
  63: { name: 'Cloak', category: 'clothes' },
  64: { name: 'Explorer Jacket', category: 'clothes' },
  65: { name: 'Golden Robe', category: 'clothes' },
  66: { name: 'Knight Armor', category: 'clothes' },
  67: { name: 'Miner Outfit', category: 'clothes' },
  68: { name: 'Royal Cape', category: 'clothes' },
  69: { name: 'Tactical Vest', category: 'clothes' },
  70: { name: 'Crusader Armor', category: 'clothes' },
  71: { name: 'Crusader Plate', category: 'clothes' },
  72: { name: 'Royal Crusader Armor', category: 'clothes' },
  73: { name: 'Templar Armor', category: 'clothes' },
  74: { name: 'Cyber', category: 'clothes' },
  75: { name: 'Leather', category: 'clothes' },
  76: { name: 'Arcane Robe', category: 'clothes' },
  77: { name: 'Wizard Cloak', category: 'clothes' },
  78: { name: 'Necromancer Cape', category: 'clothes' },
  79: { name: 'Bone Harness', category: 'clothes' },
  80: { name: 'Skeleton Pauldrons', category: 'clothes' },
  81: { name: 'Flower Lei', category: 'clothes' },
  82: { name: 'Astronaut Vest', category: 'clothes' },
  83: { name: 'Space Cadet Uniform', category: 'clothes' },
  84: { name: 'Space Master Uniform', category: 'clothes' },
  85: { name: 'Dark Mage Tunic', category: 'clothes' },
  86: { name: 'Pentagram Tunic', category: 'clothes' },
  87: { name: 'Heraldic Tunic', category: 'clothes' },
  88: { name: 'Electric Top', category: 'clothes' },
  89: { name: 'Sushi Chef Coat', category: 'clothes' },
  90: { name: 'Taco Chef Coat', category: 'clothes' },
  91: { name: 'Shrimp Chef Coat', category: 'clothes' },
  92: { name: 'Temaki Chef Coat', category: 'clothes' },
  93: { name: 'Basketball Jersey', category: 'clothes' },
  94: { name: 'Military Vest', category: 'clothes' },
  95: { name: 'Prison Outfit 001', category: 'clothes' },
  96: { name: 'Prison Outfit 003', category: 'clothes' },
  97: { name: 'Prison Outfit 004', category: 'clothes' },
  98: { name: 'HODL Tee', category: 'clothes' },
  99: { name: 'Fur Coat', category: 'clothes' },
  100: { name: 'Martial Arts Gi', category: 'clothes' },
  101: { name: 'Pirate Coat', category: 'clothes' },
  102: { name: 'Vine Wrap', category: 'clothes' },
  103: { name: 'Grim Reaper Cloak', category: 'clothes' },
  104: { name: 'Dark Energy Armor', category: 'clothes' },
  // Hands (105-190)
  105: { name: 'Drink Bottle', category: 'hand' },
  106: { name: 'Fire', category: 'hand' },
  107: { name: 'Gold Coin Pouch', category: 'hand' },
  108: { name: 'Ink Bottle', category: 'hand' },
  109: { name: 'Lighthouse Model', category: 'hand' },
  110: { name: 'Lightning', category: 'hand' },
  111: { name: 'Magic Potion Bottle', category: 'hand' },
  112: { name: 'Magic Scroll', category: 'hand' },
  113: { name: 'Magic Wand', category: 'hand' },
  114: { name: 'Miner\'s Pickaxe', category: 'hand' },
  115: { name: 'Sea Urchin', category: 'hand' },
  116: { name: 'Spray Paint Can', category: 'hand' },
  117: { name: 'Trident', category: 'hand' },
  118: { name: 'Ban Hammer', category: 'hand' },
  119: { name: 'Gold Cross Medal', category: 'hand' },
  120: { name: 'Silver Cross Medal', category: 'hand' },
  121: { name: 'Capsule', category: 'hand' },
  122: { name: 'Hot Cocoa', category: 'hand' },
  123: { name: 'Rainbow', category: 'hand' },
  124: { name: 'Snake', category: 'hand' },
  125: { name: 'Dagger', category: 'hand' },
  126: { name: 'Honey Dipper', category: 'hand' },
  127: { name: 'Fish', category: 'hand' },
  128: { name: 'Mini Octopus Gun', category: 'hand' },
  129: { name: 'Pickaxe', category: 'hand' },
  130: { name: 'Rust Pickaxe', category: 'hand' },
  131: { name: 'Blue Pickaxe', category: 'hand' },
  132: { name: 'Toilet Paper', category: 'hand' },
  133: { name: 'Cactus Pot Pink', category: 'hand' },
  134: { name: 'Cactus Pot Yellow', category: 'hand' },
  135: { name: 'Cactus Pot Purple', category: 'hand' },
  136: { name: 'Toothbrush', category: 'hand' },
  137: { name: 'Katana', category: 'hand' },
  138: { name: 'Mystery Block', category: 'hand' },
  139: { name: 'Magic Mushroom', category: 'hand' },
  140: { name: 'Emoji', category: 'hand' },
  141: { name: 'Only Up', category: 'hand' },
  142: { name: 'Red Lollipop', category: 'hand' },
  143: { name: 'Blue Lollipop', category: 'hand' },
  144: { name: 'Cheese Corn', category: 'hand' },
  145: { name: 'Donut', category: 'hand' },
  146: { name: 'Spicy Ramen', category: 'hand' },
  147: { name: 'Shrimp Ramen', category: 'hand' },
  148: { name: 'Vegetable Ramen', category: 'hand' },
  149: { name: 'Ramen', category: 'hand' },
  150: { name: 'Sushi Roll', category: 'hand' },
  151: { name: 'Chili Pepper', category: 'hand' },
  152: { name: 'Bubble Tea', category: 'hand' },
  153: { name: 'Ice Cream', category: 'hand' },
  154: { name: 'Fried Chicken', category: 'hand' },
  155: { name: 'Spicy Fried Chicken', category: 'hand' },
  156: { name: 'Honey Fried Chicken', category: 'hand' },
  157: { name: 'Magic Hourglass', category: 'hand' },
  158: { name: 'Smoked Hourglass', category: 'hand' },
  159: { name: 'Rainbow Wand', category: 'hand' },
  160: { name: 'Magic Lightning', category: 'hand' },
  161: { name: 'Hole', category: 'hand' },
  162: { name: 'Infinity Gauntlet', category: 'hand' },
  163: { name: 'Rocket', category: 'hand' },
  164: { name: 'Sushi Hand Roll', category: 'hand' },
  165: { name: 'Pizza Slice', category: 'hand' },
  166: { name: 'Pepe Book', category: 'hand' },
  167: { name: 'Magic Pepe Book', category: 'hand' },
  168: { name: 'Pepe Shield', category: 'hand' },
  169: { name: 'Double Pepe Book', category: 'hand' },
  170: { name: 'Dogecoin Shield', category: 'hand' },
  171: { name: 'Big Banana', category: 'hand' },
  172: { name: 'Keyboard', category: 'hand' },
  173: { name: 'Rubber Duck', category: 'hand' },
  174: { name: 'Ban Hammer Red', category: 'hand' },
  175: { name: 'Claws', category: 'hand' },
  176: { name: 'Golden Scepter', category: 'hand' },
  177: { name: 'Swordfish', category: 'hand' },
  178: { name: 'Electric Eel', category: 'hand' },
  179: { name: 'Coral Trident', category: 'hand' },
  180: { name: 'Pufferfish', category: 'hand' },
  181: { name: 'Candlestick Chart', category: 'hand' },
  182: { name: 'Gas Gun', category: 'hand' },
  183: { name: 'Wizard Scrolls', category: 'hand' },
  184: { name: 'Bitcoin Shield', category: 'hand' },
  185: { name: 'Crystal Sword', category: 'hand' },
  186: { name: 'Gem Hands', category: 'hand' },
  187: { name: 'Boxing Gloves', category: 'hand' },
  188: { name: 'Ice Boxing Gloves', category: 'hand' },
  189: { name: 'Ban Hammer Ice', category: 'hand' },
  190: { name: 'PHAROS Coin', category: 'hand' },
  // Eyes (191-203)
  191: { name: 'Bitcoin', category: 'eyes' },
  192: { name: 'Curved Smiling Closed', category: 'eyes' },
  193: { name: 'Dogecoin', category: 'eyes' },
  194: { name: 'Dollar', category: 'eyes' },
  195: { name: 'Normal', category: 'eyes' },
  196: { name: 'PHAROS', category: 'eyes' },
  197: { name: 'Single', category: 'eyes' },
  198: { name: 'Yellow Lightning', category: 'eyes' },
  199: { name: 'Demon', category: 'eyes' },
  200: { name: 'Blue Gem', category: 'eyes' },
  201: { name: 'Golden Gem', category: 'eyes' },
  202: { name: 'Rainbow', category: 'eyes' },
  203: { name: 'Hypnosis', category: 'eyes' },
  // Faces (204-230)
  204: { name: 'AR PHAROS', category: 'face' },
  205: { name: 'AR GMOTCHI', category: 'face' },
  206: { name: 'AR GOTCHI', category: 'face' },
  207: { name: 'Diving Googles', category: 'face' },
  208: { name: 'Gas Mask', category: 'face' },
  209: { name: 'Iron Man Mask', category: 'face' },
  210: { name: 'Tactical Face Mask', category: 'face' },
  211: { name: 'Dust Mask', category: 'face' },
  212: { name: 'AR Power', category: 'face' },
  213: { name: 'Steel Giant', category: 'face' },
  214: { name: 'Iron Giant Guard', category: 'face' },
  215: { name: 'Mad Scientist', category: 'face' },
  216: { name: 'Skeleton Demon', category: 'face' },
  217: { name: 'Pirate Eyepatch', category: 'face' },
  218: { name: 'Pirate Skull Eyepatch', category: 'face' },
  219: { name: 'Floki Beard', category: 'face' },
  220: { name: 'Beard', category: 'face' },
  221: { name: 'Band Aid', category: 'face' },
  222: { name: 'Scar', category: 'face' },
  223: { name: 'Joker', category: 'face' },
  224: { name: 'Pirate Captain Eyepatch', category: 'face' },
  225: { name: 'Forest Spirit', category: 'face' },
  226: { name: 'Neon Mask', category: 'face' },
  227: { name: 'Scanner', category: 'face' },
  228: { name: 'Coral Diving Goggles', category: 'face' },
  229: { name: 'Coinving Goggles', category: 'face' },
  230: { name: 'Camera Diving Mask', category: 'face' },
  // Mouths (231-241)
  231: { name: 'Beard', category: 'mouth' },
  232: { name: 'Big Fish', category: 'mouth' },
  233: { name: 'Fish', category: 'mouth' },
  234: { name: 'Golden Key', category: 'mouth' },
  235: { name: 'Hidden', category: 'mouth' },
  236: { name: 'Horror Doll', category: 'mouth' },
  237: { name: 'Pink Cute Smile', category: 'mouth' },
  238: { name: 'Smile', category: 'mouth' },
  239: { name: 'Smoking Pipe', category: 'mouth' },
  240: { name: 'Starfish', category: 'mouth' },
  241: { name: 'Yellow Tape', category: 'mouth' },
  // Heads (242-286)
  242: { name: 'Aviator', category: 'head' },
  243: { name: 'Captain', category: 'head' },
  244: { name: 'Cowboy', category: 'head' },
  245: { name: 'Crocodile', category: 'head' },
  246: { name: 'Crown', category: 'head' },
  247: { name: 'Dogecoin', category: 'head' },
  248: { name: 'Frog', category: 'head' },
  249: { name: 'Miner Helmet', category: 'head' },
  250: { name: 'One Piece', category: 'head' },
  251: { name: 'Orca', category: 'head' },
  252: { name: 'Panda', category: 'head' },
  253: { name: 'Pirate Bandana', category: 'head' },
  254: { name: 'Polar Bear', category: 'head' },
  255: { name: 'Sea Lion', category: 'head' },
  256: { name: 'Shark', category: 'head' },
  257: { name: 'Unicorn', category: 'head' },
  258: { name: 'Wizard Intern', category: 'head' },
  259: { name: 'Royal Navy', category: 'head' },
  260: { name: 'Royal Navy Coral', category: 'head' },
  261: { name: 'Diving Helmet', category: 'head' },
  262: { name: 'Space', category: 'head' },
  263: { name: 'Devil Horns', category: 'head' },
  264: { name: 'Barnacles', category: 'head' },
  265: { name: 'Pirate Captain', category: 'head' },
  266: { name: 'Ghost Pirate Captain', category: 'head' },
  267: { name: 'Pirate', category: 'head' },
  268: { name: 'Navy', category: 'head' },
  269: { name: 'Bandage', category: 'head' },
  270: { name: 'Prison', category: 'head' },
  271: { name: 'Casual Hat', category: 'head' },
  272: { name: 'Paper Bag', category: 'head' },
  273: { name: 'Fox Mask', category: 'head' },
  274: { name: 'Pirate Gold', category: 'head' },
  275: { name: 'Crown Of Neptune', category: 'head' },
  276: { name: 'Wizard', category: 'head' },
  277: { name: 'Royal Blue Gold Cap', category: 'head' },
  278: { name: 'Red Fez Gold Band', category: 'head' },
  279: { name: 'Golden Horn', category: 'head' },
  280: { name: 'Fire Head', category: 'head' },
  281: { name: 'Top Hat', category: 'head' },
  282: { name: 'Strawberry Head', category: 'head' },
  283: { name: 'Strawberry Head Alt', category: 'head' },
  284: { name: 'Ripe Strawberry Head', category: 'head' },
  285: { name: 'Strawberry Leaf Crown', category: 'head' },
  286: { name: 'Orange Citrus Head', category: 'head' },
};

/** Marketplace categories (excludes background, body, eyes) */
export const MARKETPLACE_CATEGORIES = ['head', 'hand', 'clothes', 'face', 'mouth'] as const;
export type MarketplaceCategory = typeof MARKETPLACE_CATEGORIES[number];

/** Get only marketplace-eligible wearables */
export function getMarketplaceWearables(): Record<number, WearableConfig> {
  const result: Record<number, WearableConfig> = {};
  for (const [id, config] of Object.entries(WEARABLE_DATA)) {
    if (MARKETPLACE_CATEGORIES.includes(config.category as MarketplaceCategory)) {
      result[Number(id)] = config;
    }
  }
  return result;
}
