export type WearableType = 'backgrounds' | 'bodys' | 'eyes' | 'hands' | 'heads' | 'clothes' | 'faces' | 'mouths';

const CDN_BASE = 'https://assets.gotchi.ai';

export const wearableNameMapping: Record<WearableType, string[]> = {
  backgrounds: [
    "Abyss",
    "Aurora Pink",
    "Bioluminescent",
    "Blood Reef",
    "Crimson Deep",
    "Cyber Void",
    "Deep Purple",
    "Ember Glow",
    "Frozen Abyss",
    "Glacial Mint",
    "Magma Core",
    "Midnight Navy",
    "Moonstone",
    "Neon Rift",
    "Ocean Depth",
    "Pearl",
    "PHAROS Gold",
    "Plasma Storm",
    "Sea Foam",
    "Sunset Coral",
    "Toxic Kelp",
    "Twilight Blue",
    "Venom Tide",
    "Void Iris",
    "Volcano Red",
  ],
  bodys: [
    "BTC Orange",
    "Orca",
    "Blue",
    "Bronze",
    "Celestial White",
    "Coral Pink",
    "Diamond",
    "ETH Purple",
    "Electric",
    "Holographic",
    "Ice Crystal",
    "Ivory",
    "Jade Green",
    "Lava",
    "Lavender",
    "Matrix Green",
    "Obsidian",
    "Ocean Blue",
    "Phantom",
    "Pink",
    "Pure Gold",
    "Neon",
    "Rose Gold",
    "Sea Green",
    "Silver Steel",
    "Sky Cyan",
    "Sunset Orange",
    "Transparent",
    "Void Black",
    "Water Body",
    "Cow",
    "Tiger",
    "Ice",
    "Galaxy",
    "Hole",
    "Bitcoin",
    "Neno",
  ],
  clothes: [
    "Camouflage Outfit",
    "Cloak",
    "Explorer Jacket",
    "Golden Robe",
    "Knight Armor",
    "Miner Outfit",
    "Royal Cape",
    "Tactical Vest",
    "Crusader Armor",
    "Crusader Plate",
    "Royal Crusader Armor",
    "Templar Armor",
    "Cyber",
    "Leather",
    "Arcane Robe",
    "Wizard Cloak",
    "Necromancer Cape",
    "Bone Harness",
    "Skeleton Pauldrons",
    "Flower Lei",
    "Astronaut Vest",
    "Space Cadet Uniform",
    "Space Master Uniform",
    "Dark Mage Tunic",
    "Pentagram Tunic",
    "Heraldic Tunic",
    "Electric Top",
    "Sushi Chef Coat",
    "Taco Chef Coat",
    "Shrimp Chef Coat",
    "Temaki Chef Coat",
    "Basketball Jersey",
    "Military Vest",
    "Prison Outfit 001",
    "Prison Outfit 003",
    "Prison Outfit 004",
    "HODL Tee",
    "Fur Coat",
    "Martial Arts Gi",
    "Pirate Coat",
    "Vine Wrap",
    "Grim Reaper Cloak",
    "Dark Energy Armor",
  ],
  hands: [
    "Drink Bottle",
    "Fire",
    "Gold Coin Pouch",
    "Ink Bottle",
    "Lighthouse Model",
    "Lightning",
    "Magic Potion Bottle",
    "Magic Scroll",
    "Magic Wand",
    "Miner's Pickaxe",
    "Sea Urchin",
    "Spray Paint Can",
    "Trident",
    "Ban Hammer",
    "Gold Cross Medal",
    "Silver Cross Medal",
    "Capsule",
    "Hot Cocoa",
    "Rainbow",
    "Snake",
    "Dagger",
    "Honey Dipper",
    "Fish",
    "Mini Octopus Gun",
    "Pickaxe",
    "Rust Pickaxe",
    "Blue Pickaxe",
    "Toilet Paper",
    "Cactus Pot Pink",
    "Cactus Pot Yellow",
    "Cactus Pot Purple",
    "Toothbrush",
    "Katana",
    "Mystery Block",
    "Magic Mushroom",
    "Emoji",
    "Only Up",
    "Red Lollipop",
    "Blue Lollipop",
    "Cheese Corn",
    "Donut",
    "Spicy Ramen",
    "Shrimp Ramen",
    "Vegetable Ramen",
    "Ramen",
    "Sushi Roll",
    "Chili Pepper",
    "Bubble Tea",
    "Ice Cream",
    "Fried Chicken",
    "Spicy Fried Chicken",
    "Honey Fried Chicken",
    "Magic Hourglass",
    "Smoked Hourglass",
    "Rainbow Wand",
    "Magic Lightning",
    "Hole",
    "Infinity Gauntlet",
    "Rocket",
    "Sushi Hand Roll",
    "Pizza Slice",
    "Pepe Book",
    "Magic Pepe Book",
    "Pepe Shield",
    "Double Pepe Book",
    "Dogecoin Shield",
    "Big Banana",
    "Keyboard",
    "Rubber Duck",
    "Ban Hammer Red",
    "Claws",
    "Golden Scepter",
    "Swordfish",
    "Electric Eel",
    "Coral Trident",
    "Pufferfish",
    "Candlestick Chart",
    "Gas Gun",
    "Wizard Scrolls",
    "Bitcoin Shield",
    "Crystal Sword",
    "Gem Hands",
    "Boxing Gloves",
    "Ice Boxing Gloves",
    "Ban Hammer Ice",
    "PHAROS Coin",
  ],
  eyes: [
    "Bitcoin",
    "Curved Smiling Closed",
    "Dogecoin",
    "Dollar",
    "Normal",
    "PHAROS",
    "Single",
    "Yellow Lightning",
    "Demon",
    "Blue Gem",
    "Golden Gem",
    "Rainbow",
    "Hypnosis",
  ],
  faces: [
    "AR PHAROS",
    "AR GMOTCHI",
    "AR GOTCHI",
    "Diving Googles",
    "Gas Mask",
    "Iron Man Mask",
    "Tactical Face Mask",
    "Dust Mask",
    "AR Power",
    "Steel Giant",
    "Iron Giant Guard",
    "Mad Scientist",
    "Skeleton Demon",
    "Pirate Eyepatch",
    "Pirate Skull Eyepatch",
    "Floki Beard",
    "Beard",
    "Band Aid",
    "Scar",
    "Joker",
    "Pirate Captain Eyepatch",
    "Forest Spirit",
    "Neon Mask",
    "Scanner",
    "Coral Diving Goggles",
    "Coinving Goggles",
    "Camera Diving Mask",
  ],
  mouths: [
    "Beard",
    "Big Fish",
    "Fish",
    "Golden Key",
    "Hidden",
    "Horror Doll",
    "Pink Cute Smile",
    "Smile",
    "Smoking Pipe",
    "Starfish",
    "Yellow Tape",
  ],
  heads: [
    "Aviator",
    "Captain",
    "Cowboy",
    "Crocodile",
    "Crown",
    "Dogecoin",
    "Frog",
    "Miner Helmet",
    "One Piece",
    "Orca",
    "Panda",
    "Pirate Bandana",
    "Polar Bear",
    "Sea Lion",
    "Shark",
    "Unicorn",
    "Wizard Intern",
    "Royal Navy",
    "Royal Navy Coral",
    "Diving Helmet",
    "Space",
    "Devil Horns",
    "Barnacles",
    "Pirate Captain",
    "Ghost Pirate Captain",
    "Pirate",
    "Navy",
    "Bandage",
    "Prison",
    "Casual Hat",
    "Paper Bag",
    "Fox Mask",
    "Pirate Gold",
    "Crown Of Neptune",
    "Wizard",
    "Royal Blue Gold Cap",
    "Red Fez Gold Band",
    "Golden Horn",
    "Fire Head",
    "Top Hat",
    "Strawberry Head",
    "Strawberry Head Alt",
    "Ripe Strawberry Head",
    "Strawberry Leaf Crown",
    "Orange Citrus Head",
  ],
};

export const wearableFileMapping: Record<WearableType, string[]> = {
  backgrounds: [
    "000-bg-Abyss",
    "001-bg-Aurora_Pink",
    "002-bg-Bioluminescent",
    "003-bg-Blood_Reef",
    "004-bg-Crimson_Deep",
    "005-bg-Cyber_Void",
    "006-bg-Deep_Purple",
    "007-bg-Ember_Glow",
    "008-bg-Frozen_Abyss",
    "009-bg-Glacial_Mint",
    "010-bg-Magma_Core",
    "011-bg-Midnight_Navy",
    "012-bg-Moonstone",
    "013-bg-Neon_Rift",
    "014-bg-Ocean_Depth",
    "015-bg-Pearl",
    "016-bg-Pharos_Gold",
    "017-bg-Plasma_Storm",
    "018-bg-Sea_Foam",
    "019-bg-Sunset_Coral",
    "020-bg-Toxic_Kelp",
    "021-bg-Twilight_Blue",
    "022-bg-Venom_Tide",
    "023-bg-Void_Iris",
    "024-bg-Volcano_Red",
  ],
  bodys: [
    "025-body_close-BTC_Orange",
    "026-body_close-Black_White",
    "027-body_close-Blue",
    "028-body_close-Bronze",
    "029-body_close-Celestial_White",
    "030-body_close-Coral_Pink",
    "031-body_close-Diamond",
    "032-body_close-ETH_Purple",
    "033-body_close-Electric",
    "034-body_close-Holographic",
    "035-body_close-Ice_Crystal",
    "036-body_close-Ivory",
    "037-body_close-Jade_Green",
    "038-body_close-Lava",
    "039-body_close-Lavender",
    "040-body_close-Matrix_Green",
    "041-body_close-Obsidian",
    "042-body_close-Ocean_Blue",
    "043-body_close-Phantom",
    "044-body_close-Pink",
    "045-body_close-Pure_Gold",
    "046-body_close-Neno",
    "047-body_close-Rose_Gold",
    "048-body_close-Sea_Green",
    "049-body_close-Silver_Steel",
    "050-body_close-Sky_Cyan",
    "051-body_close-Sunset_Orange",
    "052-body_close-Transparent",
    "053-body_close-Void_Black",
    "054-body_close-Water_Body",
    "055-body-cow",
    "056-body-tiger",
    "057-body-ice",
    "058-body-galaxy",
    "059-body-hole",
    "060-body-bitcoin",
    "061-body-rainbow",
  ],
  clothes: [
    "062-clothes-Camouflage_Outfit",
    "063-clothes-Cloak",
    "064-clothes-Explorer_Jacket",
    "065-clothes-Golden_Robe",
    "066-clothes-Knight_Armor",
    "067-clothes-Miner_Outfit",
    "068-clothes-Royal_Cape",
    "069-clothes-Tactical_Vest",
    "070-clothes-Crusader_Armor",
    "071-clothes-Crusader_Plate",
    "072-clothes-Royal_Crusader_Armor",
    "073-clothes-Templar_Armor",
    "074-clothes-Cyber",
    "075-clothes-Leather",
    "076-clothes-Arcane_Robe",
    "077-clothes-Wizard_Cloak",
    "078-clothes-Necromancer_Cape",
    "079-clothes-Bone_Harness",
    "080-clothes-Skeleton_Pauldrons",
    "081-clothes-Flower_Lei",
    "082-clothes-Astronaut_Vest",
    "083-clothes-Space_Cadet_Uniform",
    "084-clothes-Space_Master_Uniform",
    "085-clothes-Dark_Mage_Tunic",
    "086-clothes-Pentagram_Tunic",
    "087-clothes-Heraldic_Tunic",
    "088-clothes-Electric_Top",
    "089-clothes-Sushi_Chef_Coat",
    "090-clothes-Taco_Chef_Coat",
    "091-clothes-Shrimp_Chef_Coat",
    "092-clothes-Temaki_Chef_Coat",
    "093-clothes-Basketball_Jersey",
    "094-clothes-Military_Vest",
    "095-clothes-Prison_Outfit_001",
    "096-clothes-Prison_Outfit_003",
    "097-clothes-Prison_Outfit_004",
    "098-clothes-HODL_Tee",
    "099-clothes-Fur_Coat",
    "100-clothes-Martial_Arts_Gi",
    "101-clothes-Pirate_Coat",
    "102-clothes-Vine_Wrap",
    "103-clothes-Grim_Reaper_Cloak",
    "104-clothes-Dark_Energy_Armor",
  ],
  hands: [
    "105-hand-Drink_Bottle",
    "106-hand-Fire",
    "107-hand-Gold_Coin_Pouch",
    "108-hand-Ink_Bottle",
    "109-hand-Lighthouse_Model",
    "110-hand-Lightning",
    "111-hand-Magic_Potion_Bottle",
    "112-hand-Magic_Scroll",
    "113-hand-Magic_Wand",
    "114-hand-Miner's_Pickaxe",
    "115-hand-Sea_Urchin",
    "116-hand-Spray_Paint_Can",
    "117-hand-Trident",
    "118-hand-Ban_Hammer",
    "119-hand-Gold_Cross_Medal",
    "120-hand-Silver_Cross_Medal",
    "121-hand-Capsule",
    "122-hand-Hot_Cocoa",
    "123-hand-Rainbow",
    "124-hand-Snake",
    "125-hand-Dagger",
    "126-hand-Honey_Dipper",
    "127-hand-Fish",
    "128-hand-Mini_Octopus_Gun",
    "129-hand-Pickaxe",
    "130-hand-Rust_Pickaxe",
    "131-hand-Blue_Pickaxe",
    "132-hand-Toilet_Paper",
    "133-hand-Cactus_Pot_Pink",
    "134-hand-Cactus_Pot_Yellow",
    "135-hand-Cactus_Pot_Purple",
    "136-hand-Toothbrush",
    "137-hand-Katana",
    "138-hand-Mystery_Block",
    "139-hand-Magic_Mushroom",
    "140-hand-emoji",
    "141-hand-Only_up",
    "142-hand-Red_Lollipop",
    "143-hand-Blue_Lollipop",
    "144-hand-Cheese_Corn",
    "145-hand-Donut",
    "146-hand-Spicy_Ramen",
    "147-hand-Shrimp_Ramen",
    "148-hand-Vegetable_Ramen",
    "149-hand-Ramen",
    "150-hand-Sushi_Roll",
    "151-hand-Chili_Pepper",
    "152-hand-Bubble_Tea",
    "153-hand-Ice_Cream",
    "154-hand-Fried_Chicken",
    "155-hand-Spicy_Fried_Chicken",
    "156-hand-Honey_Fried_Chicken",
    "157-hand-Magic_Hourglass",
    "158-hand-Smoked_Hourglass",
    "159-hand-Rainbow_Wand",
    "160-hand-Magic_Lightning",
    "161-hand-Hole",
    "162-hand-Infinity_Gauntlet",
    "163-hand-Rocket",
    "164-hand-Sushi_Hand_Roll",
    "165-hand-Pizza_Slice",
    "166-hand-Pepe_Book",
    "167-hand-Magic_Pepe_Book",
    "168-hand-Pepe_Shield",
    "169-hand-Double_Pepe_Book",
    "170-hand-Dogecoin_Shield",
    "171-hand-Big_Banana",
    "172-hand-Keyboard",
    "173-hand-Rubber_Duck",
    "174-hand-Ban_Hammer_Red",
    "175-hand-Claws",
    "176-hand-Golden_Scepter",
    "177-hand-Swordfish",
    "178-hand-Electric_Eel",
    "179-hand-Coral_Trident",
    "180-hand-Pufferfish",
    "181-hand-Candlestick_Chart",
    "182-hand-Gas_Gun",
    "183-hand-Wizard_Scrolls",
    "184-hand-Bitcoin_Shield",
    "185-hand-Crystal_Sword",
    "186-hand-Gem_Hands",
    "187-hand-Boxing_Gloves",
    "188-hand-Ice_Boxing_Gloves",
    "189-hand-Ban_Hammer_Ice",
    "190-hand-pharos_coin",
  ],
  eyes: [
    "191-eye-Bitcoin",
    "192-eye-Curved_Smiling_Closed",
    "193-eye-Dogecoin",
    "194-eye-Dollar",
    "195-eye-Normal",
    "196-eye-Pharos",
    "197-eye-Single",
    "198-eye-Yellow_Lightning",
    "199-eye-Demon",
    "200-eye-Blue_Gem",
    "201-eye-Golden_Gem",
    "202-eye-Rainbow",
    "203-eye-Hypnosis",
  ],
  faces: [
    "204-face-AR_PHAROS",
    "205-face-AR_GMOTCHI",
    "206-face-AR_GOTCHI",
    "207-face-Diving_Googles",
    "208-face-Gas_Mask",
    "209-face-Iron_Man_Mask",
    "210-face-Tactical_Face_Mask",
    "211-face-Dust_Mask",
    "212-face-AR_Power",
    "213-face-Steel_Giant",
    "214-face-Iron_Giant_Guard",
    "215-face-Mad_Scientist",
    "216-face-Skeleton_Demon",
    "217-face-Pirate_Eyepatch",
    "218-face-Pirate_Skull_Eyepatch",
    "219-face-Floki_Beard",
    "220-face-Beard",
    "221-face-Band_Aid",
    "222-face-Scar",
    "223-face-Joker",
    "224-face-Pirate_Captain_Eyepatch",
    "225-face-Forest_Spirit",
    "226-face-Neon_Mask",
    "227-face-Scanner",
    "228-face-Coral_Diving_Goggles",
    "229-face-Coinving_Goggles",
    "230-face-Camera_Diving_Mask",
  ],
  mouths: [
    "231-mouth-Beard",
    "232-mouth-Big_Fish",
    "233-mouth-Fish",
    "234-mouth-Golden_Key",
    "235-mouth-Hidden",
    "236-mouth-Horror_Doll",
    "237-mouth-Pink_Cute_Smile",
    "238-mouth-Smile",
    "239-mouth-Smoking_Pipe",
    "240-mouth-Starfish",
    "241-mouth-Yellow_Tape",
  ],
  heads: [
    "242-head-Aviator",
    "243-head-Captain",
    "244-head-Cowboy",
    "245-head-Crocodile",
    "246-head-Crown",
    "247-head-Dogecoin",
    "248-head-Frog",
    "249-head-Miner_Helmet",
    "250-head-One_Piece",
    "251-head-Orca",
    "252-head-Panda",
    "253-head-Pirate_Bandana",
    "254-head-Polar_Bear",
    "255-head-Sea_Lion",
    "256-head-Shark",
    "257-head-Unicorn",
    "258-head-Wizard_Intern",
    "259-head-Royal_Navy",
    "260-head-Royal_Navy_Coral",
    "261-head-Diving_Helmet",
    "262-head-Space",
    "263-head-Devil_Horns",
    "264-head-Barnacles",
    "265-head-Pirate_Captain",
    "266-head-Ghost_Pirate_Captain",
    "267-head-Pirate",
    "268-head-Navy",
    "269-head-Bandage",
    "270-head-Prison",
    "271-head-Casual_Hat",
    "272-head-Paper_Bag",
    "273-head-Fox_Mask",
    "274-head-Pirate_Gold",
    "275-head-Crown_of_Neptune",
    "276-head-Wizard",
    "277-head-Royal_Blue_Gold_Cap",
    "278-head-Red_Fez_Gold_Band",
    "279-head-Golden_Horn",
    "280-head-Fire_Head",
    "281-head-Top_Hat",
    "282-head-Strawberry_Head",
    "283-head-Strawberry_Head_Alt",
    "284-head-Ripe_Strawberry_Head",
    "285-head-Strawberry_Leaf_Crown",
    "286-head-Orange_Citrus_Head",
  ],
};

export const WEARABLE_TYPE_OFFSETS: Record<WearableType, number> = {
  backgrounds: 0,
  bodys: 25,
  clothes: 62,
  hands: 105,
  eyes: 191,
  faces: 204,
  mouths: 231,
  heads: 242,
};

export const TOTAL_WEARABLES = 287;

/**
 * Get R2 SVG file name by type and local index
 */
export const getWearableFileName = (type: WearableType, index: number): string => {
  const files = wearableFileMapping[type];
  if (index >= 0 && index < files.length) {
    return files[index];
  }
  return files[0];
};

/**
 * Get wearable SVG URL from R2 CDN
 * For bodys, returns body_close variant by default
 */
export const getWearableSvgUrl = (type: WearableType, index: number, bodyVariant: 'body_close' | 'body_open' = 'body_close'): string => {
  const fileName = getWearableFileName(type, index);
  if (type === 'bodys') {
    const dir = bodyVariant;
    const actualFileName = bodyVariant === 'body_open'
      ? fileName.replace('body_close', 'body_open')
      : fileName;
    return `${CDN_BASE}/svg/${dir}/${actualFileName}.svg`;
  }
  return `${CDN_BASE}/svg/${type}/${fileName}.svg`;
};

/**
 * Get wearable PNG URL from R2 CDN for gotchi preview rendering
 * For bodys, returns body_close or body_open variant
 */
export const getWearablePngUrl = (type: WearableType, index: number, bodyVariant: 'body_close' | 'body_open' = 'body_close'): string => {
  const fileName = getWearableFileName(type, index);
  if (type === 'bodys') {
    const dir = bodyVariant;
    const actualFileName = bodyVariant === 'body_open'
      ? fileName.replace('body_close', 'body_open')
      : fileName;
    return `${CDN_BASE}/png/${dir}/${actualFileName}.png`;
  }
  return `${CDN_BASE}/png/${type}/${fileName}.png`;
};

/**
 * Get wearable preview image path (PNG) from R2 CDN
 */
export const getWearableImagePath = (type: WearableType, index: number): string => {
  const fileName = getWearableFileName(type, index);
  const actualFileName = type === 'bodys' ? fileName.replace('body_close', 'body') : fileName;
  return `${CDN_BASE}/wearables/${type}/${actualFileName}.png`;
};

/**
 * Get wearable display name by local index
 */
export const getWearableName = (type: WearableType, index: number): string => {
  const names = wearableNameMapping[type];
  if (index >= 0 && index < names.length) {
    return names[index];
  }
  return 'Unknown';
};

