
export function cleanAIText(text: string): string {
  if (!text) return '';

  let cleaned = text
    .replace(/\*\*\s*\*\s*([^*]+?):\s*\*\*/g, '**$1:**')
    .replace(/\*\*\s*\*\s*([^*]+?):\s*\*\*\s*/g, '**$1:**\n')
    .replace(/\*\*\*([^*]+?):\*\*/g, '**$1:**')
    .replace(/\*\*([^*]+?)\s*:\s*\*\*/g, '**$1:**')
    .replace(/\*\*\s*\*\s*([^*]+?):\s*\*\*\s*\*/g, '**$1:**')
    .replace(/([.,;:!?])([A-Z])/g, '$1 $2')
    .replace(/\)([A-Za-z])/g, ') $1')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/d\s+Apps/g, 'dApps')
    .replace(/De\s+Fi/g, 'DeFi')
    .replace(/\*\*Key Features:\s*\*\*\s*\*/g, '**Key Features:**')
    .replace(/\*\*Modular Stack:\s*\*\*\s*\*/g, '**Modular Stack:**')
    .replace(/\*\*Ethereum Compatibility:\s*\*\*\s*\*/g, '**Ethereum Compatibility:**')
    .replace(/\*\*Data Layer:\s*\*\*\s*\*/g, '**Data Layer:**')
    .replace(/\*\*Consensus Layer:\s*\*\*\s*\*/g, '**Consensus Layer:**')
    .replace(/\*\*Transaction Layer:\s*\*\*\s*\*/g, '**Transaction Layer:**')
    .replace(/\*\*Use Cases:\s*\*\*\s*\*/g, '**Use Cases:**')
    .replace(/\*\*Benefits:\s*\*\*\s*\*/g, '**Benefits:**')
    .replace(/\*\*Overview:\s*\*\*\s*\*/g, '**Overview:**')
    .replace(/\*\*Features:\s*\*\*\s*\*/g, '**Features:**')
    .replace(/\*\*\s*\*([^*]+?)\*\*\s*\*/g, '**$1:**')
    .replace(/\*\*\s*\*([^*]+?)\*\*\s*/g, '**$1:**')
    .replace(/\*\*\s*\*([^*]+?)\*\*$/g, '**$1:**')
    .replace(/\*\*\*([^*]+):\s*\*\*\*/g, '**$1:**')
    .replace(/\*\*([^*]+):\s*\*\*/g, '**$1:**')
    .replace(/\*\*\*([^*]+):\s*\*\*/g, '**$1:**')
    .replace(/\*\s+\*/g, '**')
    .replace(/\*\*\s+\*\*/g, '**')
    .replace(/\*\*\*\s+\*\*\*/g, '***')
    .replace(/^\s*\*\s+\*\s+\*\s+([^*\n]+)/gm, '* $1')
    .replace(/^\s*\*\s+\*\s+([^*\n]+)/gm, '* $1')
    .replace(/\n\s*\*\s+\*\s+\*\s+([^*\n]+)/g, '\n* $1')
    .replace(/\n\s*\*\s+\*\s+([^*\n]+)/g, '\n* $1')
    .replace(/\*\*\*([^*]+)\*\*\*\.\*\*\*/g, '**$1.**')
    .replace(/\*\*([^*]+)\*\*\.\*\*/g, '**$1.**')
    .replace(/\*\*\*([^*]+)\*\*\*\.\*\*\*([^*]+)\*\*\*/g, '**$1.** **$2:**')
    .replace(/\*\*\*([^*]+)\*\*\*\.\*\*\*([^*]+)\*\*\*\.\*\*\*/g, '**$1.** **$2.**')
    .replace(/([^*\n]+)\*\*\*\.\*\*\*([^*\n]+)/g, '$1. $2')
    .replace(/([^*\n]+)\*\*\.\*\*([^*\n]+)/g, '$1. $2')
    .replace(/```\s*\*\s*/g, '```')
    .replace(/\s*\*\s*```/g, '```')
    .replace(/\n\s*\n\s*\n+/g, '\n\n')
    .replace(/\n\s*\*\s*\n/g, '\n\n');

  return cleaned.trim();
}
